### ISSUE TITLE
In the scenario text file, when I use landuse+ but do not use biomass-harvest, I get a stack trace error (error below)

### ISSUE THREAD

**Issue by Baguage** [LANDIS-II-Foundation/Extension-Land-Use-Change#2]
Reported by Matthew Duveneck

It looks like the updates that were made in the last couple weeks to Biomass Harvest 3.0 and PnET-Succession have fixed both the partial harvesting problem in biomass harvest that I found AND the partial harvesting problem in landuse+. I have tested this and show partial harvest removal successful in both disturbance extensions.

There is a problem though

2) In the scenario text file, when I use landuse+ but do not use biomass-harvest, I get a stack trace error (error below).  When I run biomass harvest AND landuse+, I don't get an error and everything seems to run. As a hack, I can run biomass Harvest with zero biomass removed and then turn on landuse+ successfully.

2015-10-13 13:53:00,973 - LANDIS-II 6.1 (official release)
2015-10-13 13:53:00,990 - 
2015-10-13 13:53:01,118 - Loading scenario from file "HEM_scenario_pnet_orig.txt" ...
2015-10-13 13:53:01,222 - Initialized random number generator with user-supplied seed = 4,357
2015-10-13 13:53:01,222 - Loading species data from file "NE_species.txt" ...
2015-10-13 13:53:01,256 - Loading ecoregions from file "HEM_ecoregions.txt" ...
2015-10-13 13:53:01,283 - Initializing landscape from ecoregions map "HEM_314_single_cell_eco.img" ...
2015-10-13 13:53:01,309 - Cell length = 100 m, cell area = 1 ha
2015-10-13 13:53:01,311 - Map dimensions: 1 row by 1 column = 1 cell
2015-10-13 13:53:01,323 - Sites: 1 active (100.0 %), 0 inactive (0.0 %)
2015-10-13 13:53:01,337 - Loading PnET-Succession extension ...
2015-10-13 13:53:01,394 - OutputSite (1, 1) ecoregion eco314
2015-10-13 13:53:01,405 - Initializing PnET-Succession version 1.0.0.0
2015-10-13 13:53:01,478 - Eco SoiltWiltPntFieldCap(mm)FC-WPPorosity
2015-10-13 13:53:01,479 - eco314 SALO65.12118150.858685.73742360.9474
2015-10-13 13:53:01,498 -    Registering Data:  TimeOfLastSuccession.
2015-10-13 13:53:01,499 -    Registering Data:  Shade.
2015-10-13 13:53:01,501 -    Creating Dispersal Neighborhood List.
2015-10-13 13:53:01,502 -    Dispersal:  NeighborRadius=5050, CellLength=100, numCellRadius=50
2015-10-13 13:53:01,509 - Spinning up biomass
2015-10-13 13:53:01,511 -    Loading initial communities from file "HEM_initial_community.txt" ...
2015-10-13 13:53:01,526 -    Reading initial communities map "single_cell_IC_val10.img" ...
2015-10-13 13:53:01,699 -    Registering Data:  Succession.BiomassCohorts.
2015-10-13 13:53:01,699 -    Registering Data:  Succession.WoodyDebris.
2015-10-13 13:53:01,699 -    Registering Data:  Succession.Litter.
2015-10-13 13:53:01,700 -    Registering Data:  Succession.AgeCohorts.
2015-10-13 13:53:01,700 -    Registering Data:  Succession.CohortsPnET.
2015-10-13 13:53:01,703 - Loading Land Use 1.0 extension ...
2015-10-13 13:53:01,715 -   Loading parameters from landuse_plus_single_cell.txt
2015-10-13 13:53:01,768 - Initializing Land Use...
2015-10-13 13:53:01,769 -    Registering Data:  LandUse.AllowHarvest.
2015-10-13 13:53:01,771 -   Opening log file "land-use/site-log.csv"...
2015-10-13 13:53:01,779 -   Reading map "land-use8S_0.img"...
2015-10-13 13:53:01,797 -     Forest (1)
2015-10-13 13:53:01,797 - Loading Output-PnET extension ...
2015-10-13 13:53:01,813 - Running Output-PnET ...
2015-10-13 13:53:01,843 - Current time: 1
2015-10-13 13:53:01,844 - Running PnET-Succession ...
2015-10-13 13:53:01,892 - Current time: 2
2015-10-13 13:53:01,892 - Running PnET-Succession ...
2015-10-13 13:53:01,909 - Current time: 3
2015-10-13 13:53:01,909 - Running PnET-Succession ...
2015-10-13 13:53:01,924 - Current time: 4
2015-10-13 13:53:01,925 - Running PnET-Succession ...
2015-10-13 13:53:01,941 - Current time: 5
2015-10-13 13:53:01,941 - Running PnET-Succession ...
2015-10-13 13:53:01,956 - Running Output-PnET ...
2015-10-13 13:53:01,957 - Current time: 6
2015-10-13 13:53:01,957 - Running PnET-Succession ...
2015-10-13 13:53:01,973 - Current time: 7
2015-10-13 13:53:01,973 - Running PnET-Succession ...
2015-10-13 13:53:01,989 - Current time: 8
2015-10-13 13:53:01,989 - Running PnET-Succession ...
2015-10-13 13:53:02,006 - Current time: 9
2015-10-13 13:53:02,007 - Running PnET-Succession ...
2015-10-13 13:53:02,021 - Current time: 10
2015-10-13 13:53:02,022 - Running Land Use ...
2015-10-13 13:53:02,023 -   Reading map "land-use8S_10.img"...
2015-10-13 13:53:02,045 - Internal error occurred within the program:
2015-10-13 13:53:02,046 -   Object reference not set to an instance of an object.
2015-10-13 13:53:02,046 - 
2015-10-13 13:53:02,047 - Stack trace:
2015-10-13 13:53:02,050 -    at Landis.Library.BiomassHarvest.PartialCohortCutter.Cut(ActiveSite site, CohortCounts cohortCounts)
   at Landis.Extension.LandUse.LandCover.RemoveTrees.ApplyTo(ActiveSite site)
   at Landis.Extension.LandUse.Main.<Run>b__2(Site site, LandUse newLandUse)
   at Landis.Extension.LandUse.Main.ProcessInputMap(ProcessLandUseAt processLandUseAt)
   at Landis.Extension.LandUse.Main.Run()
   at Landis.Model.Run(ExtensionMain extension)
   at Landis.Model.Run(String scenarioPath, IUserInterface ui)
   at Landis.App.Main(String[] args)

**Comment by brmiranda** [comment]
Version 1.1 appears to have resolved this issue.  Simulations run with Land Use, but not Biomass Harvest do not throw any errors.
